export * from './sections/CategoriesStrip'
export * from './sections/BenefitsStrip'
export * from './sections/BlogShowcase'
export * from './sections/InfoWithCounters'
export * from './sections/InfoWithImageLeft'
export * from './sections/FAQ'
export { HeroSlider } from './sections/Hero/HeroSlider.component'
export { InfoWithImageRight } from './sections/InfoWithImageRight/InfoWithImageRight'
